export const actionType = {
    SET_HEADER_TITLE: 'SET_HEADER_TITLE',
    SET_CAMERA: 'SET_CAMERA',
    SET_METERNO: 'SET_METERNO',
    SET_DEVICENO: 'SET_DEVICENO',
    SET_CAMERATYPE: 'SET_CAMERATYPE',
    SET_REGISTER: 'SET_REGISTER',
    SET_CHECK:"SET_CHECK"
	
	

}